### ISSUE TITLE
Checkmarks displayed on all playlists while adding/removing track

### ISSUE THREAD

**Issue by hakanto** [resonatecoop/stream2own#104]
### Operating system
Linux: Pop!_OS 21.04

### Browser name and version
Brave: Version 1.16.68 Chromium: 86.0.4240.111 (Official Build) (64-bit)

### Expected behavior
Went to remove a track from one of my playlists. Accessed popup menu on the playlist page. On the popup menu, checkmarks would only show on those playlists which featured the track.

### Actual behavior
Went to remove a track from one of my playlists. Accessed popup menu on the playlist page. On the popup menu, checkmarks displayed on all playlists, even those which did not feature the track.

### Steps to reproduce behavior
Go to a playlist which has tracks. Click threedot menu next to track and open playlist popup menu. Behold!

**Comment by hakanto** [comment]
@auggod @whatSocks I was able to remove tracks from playlists by clicking the checkmark of the correct playlist.

I did some further testing and discovered that I can't add tracks to playlists! Same thing, on the Add To Playlist popup, all playlists are checked and I'm unable to click them to add the tracks.

**Comment by auggod** [comment]
The API swagger definition had some missing query parameter info. Should have been there when we merged #100. The API is now returning the expected data.
