### ISSUE TITLE
[mobile] [safari]

### ISSUE THREAD

**Issue by whatSocks** [resonatecoop/stream2own#109]
### Operating system
iOS 

### Browser name and version
Safari

### Expected behavior
x icon in search bar should be similar size as the magnifying glass icon 

### Actual behavior
it's like the size of a couple pixels

### Steps to reproduce behavior

on mobile iOS, use the search functionality. Look for the x to dismiss search

<img width="331" alt="Screen Shot 2021-10-15 at 6 19 58 PM" src="https://user-images.githubusercontent.com/2731744/137559499-e49c1fb0-db95-4200-a7ba-a04281a88e31.png">

**Comment by auggod** [comment]
Depending of iOs version it's even worse. I was able to check on an old ipad but it was not updated for some time. ~~I may be able to debug this tomorrow.~~ (didn't have time)
