### ISSUE TITLE
For non-authed visitors, prompt: "Log in to listen to full song"

### ISSUE THREAD

**Issue by hakanto** [resonatecoop/stream2own#115]
We need a simple way to alert non-logged in users that they need to log in to listen to more than 45 second previews. Here's some mockups of what it could look like and how it could function.

Design: If user is not logged in and is listening to a song preview, a bar displays just above the player control area while listening to a 45 second song preview. The bar states "Log in to listen to full song". The bar disappears when 45 second playback ends or playback is turned off by user.

If easier to program, the bar could instead stay visible at all times to non-logged in users. Most important thing is just to get the message out there so that new users understand that the player is functioning as designed and they need to log in to hear full tracks.

![loginprompt_blackbg](https://user-images.githubusercontent.com/72839766/138740282-8c2d1b78-0860-4148-b497-6d8e979ca315.png)

![loginprompt_white](https://user-images.githubusercontent.com/72839766/138740284-154d5e02-d79a-4fcb-b1a5-6b011b34dff2.png)

**Comment by mcfiredrill** [comment]
Taking a shot at this :fork_and_knife:

**Comment by hakanto** [comment]
If setting up the two different color options is complicated (for light mode and dark mode), alternatively you could use a grey bar with white text for both light mode and dark mode. The grey bar would be a little less stylish and not stand out as clearly, but still fine as a fallback option.

**Comment by hakanto** [comment]
@mcfiredrill How's this coming along? Any roadblocks come up?

**Comment by mcfiredrill** [comment]
@hakanto 
![line_20220105_103559](https://user-images.githubusercontent.com/66243/148270643-c432f5d1-7e03-4d17-b126-c434c0498430.png)

Here's what I have so far, I'll throw a PR up with what I have.
I haven't converted it to work with dark mode, but is it possible to change themes when you aren't logged in ?

**Comment by hakanto** [comment]
> is it possible to change themes when you aren't logged in

@mcfiredrill Good point! Nevermind on the dark mode version.

This is looking great. For the next version, can you make it white text on a black bar rather than black text on a white bar? I think the contrast with the white background will help the message stand out.
