### ISSUE TITLE
 For non-authed visitors, "Join now" button on main page near title text

### ISSUE THREAD

**Issue by hakanto** [resonatecoop/stream2own#116]
It is unclear for a non-authed user with no experience on the Player to know how to join. A join button somewhere near the main text on the Discover page will make it much easier for visitors to join and understand their relationship with the site. Having the [Join now] button right next to the word "members" can intutively express that you yourself can become a member and "own and run" the platform as mention.

When logged in, the button would not appear.

![joinbutton_frontpage](https://user-images.githubusercontent.com/72839766/138744954-a50947ba-d89a-4d30-a628-71ce9a207e79.png)

**Comment by webwelten** [comment]
Hey, I'd like to do this as a first ask. Can you assign me to it? :)

**Comment by hakanto** [comment]
@webwelten Assigned. Much thanks! :)

**Comment by webwelten** [comment]
Thanks :) I have started looking into the task.

<img width="435" alt="Screenshot 2021-11-08 at 18 16 58" src="https://user-images.githubusercontent.com/3693161/140789827-7324e4ce-3533-4b06-a756-ebae2608972f.png">

Using the css/design system it looks a bit different than in the screenshot. 
Is that alright or do we want it to be accurate?

**Comment by auggod** [comment]
It should not have this inset outline. The link can have the same styling as the LOG IN link on the bottom right.
You can also choose to use a big underline using border style instead.

**Comment by webwelten** [comment]
Alright, thanks for the clarification. Prepared it locally and couldn't push my branch to github. Do you need to give me the rights for that?

**Comment by hakanto** [comment]
@auggod @whatSocks What's the next step?

**Comment by auggod** [comment]
@webwelten Please fork resonatecoop/stream first then you should be able to pull request.

**Comment by peterklingelhofer** [comment]
@webwelten, if you are still having difficulty creating the pull request on this repository you could post your diff (`git diff` in your console) and one of us would be happy to put it together into a merge request on your behalf.

**Comment by peterklingelhofer** [comment]
Closing this issue, as #196 has been merged.
