### ISSUE TITLE
Make player theme selection more intuitive & straightforward 

### ISSUE THREAD

**Issue by douellette20** [resonatecoop/stream2own#123]
### Operating system
Linux Mint 20.2 Cinnamon

### Browser name and version
Firefox 94.0

### Expected behavior
"Auto" theme should be one of three equally selectable options, along with "Light" and "Dark", and should be the default.

### Actual behavior
"Auto" theme is a toggle switch, and greys out (but does not deselect) "Light" and "Dark" options when turned on. Switching back to "Light" or "Dark" is not possible until the "Auto" switch is turned off. "Light" theme is the default (and only option when logged out).

### Steps to reproduce behavior
While logged in to the player, open the menu at the upper right hand side. Selecting the "auto" theme, prevents "light" or "dark" from being selected until "auto" is unchecked. These options are greyed out, but circle next to the previously selected option is still filled in, leading to the possibility of an auto dark theme, while a greyed out "light" is still shown as selected, or vice versa.

**Comment by peterklingelhofer** [comment]
Hello, please assign this issue to me, as I've submitted a pull request to address this: https://github.com/resonatecoop/stream/pull/127. Thank you!
