### ISSUE TITLE
pretty social unfurl for artist, label, trackgroup

### ISSUE THREAD

**Issue by whatSocks** [resonatecoop/stream2own#129]
### Operating system
twitter

### Expected behavior

user should be able to paste a url to an artist, label, or trackgroup to twitter and see a pretty unfurl with an image

### Actual behavior

no image

**Comment by caprenter** [comment]
I think there is something not quite working here.

The following do NOT produce nice twitter cards - testing at https://cards-dev.twitter.com/validator
https://stream.resonate.coop/artist/17709
https://stream.resonate.coop/artist/17709/release/reclaim-these-streets

(I seem to be able to find many examples like this)

But this does:
https://stream.resonate.coop/artist/718/release/acid-sauna

I can't quite see why. 
The images have slightly different paths in the twitter:image meta data:
https://static.resonate.is/track-artwork/600x600/aa9a551b-d0c7-4ae0-b21b-0cbe44545d30
https://upload.resonate.is/images/75bf2360-cd10-4c72-a839-8dfed20671b7-x1500.webp

Any ideas?
