### ISSUE TITLE
Arrows showing on top of the "Add Credits" button

### ISSUE THREAD

**Issue by fgblomqvist** [resonatecoop/stream2own#141]
### Operating system
Windows 10

### Browser name and version
Firefox 96.0

### Expected behavior
For there not to be "random" arrows on the button

### Actual behavior
![bug](https://user-images.githubusercontent.com/649260/150035615-b91ce74b-d67e-4e15-ac5b-26406bf4ce7d.png)

### Steps to reproduce behavior
1. Login
2. Hover over profile menu icon
3. See the arrows on top of the "Add Credits" button

Looks like a number input is used to display the amount of credits one has, and the arrows is coming from it. Is it like that for a reason? Or can just a formatted div/span be used? I can submit a PR with a fix, just let me know 🙂

**Comment by peterklingelhofer** [comment]
I've seen this bug on my machine as well. Definitely don't think that's the intended spot for the arrows.

**Comment by fgblomqvist** [comment]
I suspect the input was perhaps used to make the formatting be automatic, or something like that. But yeah I'd say using just formatted text is probably the better move unless there's something else with the input that's desired.

**Comment by peterklingelhofer** [comment]
Appears to be a duplicate issue here: #142.
