### ISSUE TITLE
Artist and label pictures not loading

### ISSUE THREAD

**Issue by fgblomqvist** [resonatecoop/stream2own#143]
### Operating system
macOS

### Browser name and version
Firefox 95

### Expected behavior
For pictures to load or perhaps a decent placeholder?

### Actual behavior
It tries to load pictures but fails.

![Screen Shot 2022-01-19 at 6 15 20 PM](https://user-images.githubusercontent.com/649260/150181156-8cdd8b50-77b7-47e7-b0fa-22ce732300bc.png)

### Steps to reproduce behavior
Visit e.g. https://stream.resonate.coop/labels.

**Comment by peterklingelhofer** [comment]
This seems like it could potentially be related to the cover art is null issue? #139

**Comment by fgblomqvist** [comment]
Hmm yeah could be. Though it [sounded like it had been fixed already](https://community.resonate.is/t/interface-bugs-when-purchasing-credits-or-creating-a-playlist/2300/9) 🤔. Though, since the issue is still open maybe not.

**Comment by auggod** [comment]
I fixed it as soon as I realised. Data volume attached to server got unmounted.
