### ISSUE TITLE
Adding a track to "Favorites" doesn't display it in the Favorite tab of the user's Library section

### ISSUE THREAD

**Issue by IamUpInTheCloud** [resonatecoop/stream2own#144]
### Operating system
Windows 11/10

### Browser name and version
Chrome / Firefox / Opera

### Expected behavior
Adding a favorite track makes the track appear in the "favorite" tab of the user's "Library" section.

### Actual behavior
Adding a favorite track displays "track has been added to favorites" (and you can even "unfavorite" the track) correctly but nothing appears in the "favorite" tab of the user's Library section, it just says "you don't have any favorites".

### Steps to reproduce behavior
Just add a favorite track and go to "favorites" in the "Library" section.

**Comment by fgblomqvist** [comment]
I can reproduce. However, this worked fine a few days ago, so perhaps a regression somewhere?

**Comment by IamUpInTheCloud** [comment]
Just an update to mention that I'm now at a point (I've started with newer tracks and I'm moving further back in the whole catalogue) where some songs do seem to appear in favorites, but others still don't. and I think I've noticed a pattern which is that recent tracks can't be added to favorites when older ones do. Worth investigating.

**Comment by peterklingelhofer** [comment]
This could also perhaps be related to #139 and #143? It seemed that @auggod said [here](https://community.resonate.is/t/interface-bugs-when-purchasing-credits-or-creating-a-playlist/2300/9) that it was an issue with cover art being null for newer tracks (and seemingly, not null for tracks uploaded not as recently). I know @auggod resolved the original issue but just wanted to point out that this appears to be a similar pattern!

**Comment by hakanto** [comment]
Got a report in the main inbox of the same issue.

**Comment by peterklingelhofer** [comment]
Was this fixed recently? This seems to be working as intended for me after yesterday evening. Anyone else?

**Comment by auggod** [comment]
Yes, I have released an update yesterday which fix the issue. In fact the player is currently in sync with latest changes on #development
