### ISSUE TITLE
Playcounts are not fetched for all tracks on the label page

### ISSUE THREAD

**Issue by fgblomqvist** [resonatecoop/stream2own#153]
### Operating system
N/A

### Browser name and version
Firefox 96

### Expected behavior
The playcount should be accurate wherever it is displayed.

### Actual behavior
https://community.resonate.is/t/help-bug-verification-listen-count-not-reflected-on-label-page/2328

In short, on the label page, the front-end doesn't fetch the playcount for all tracks, but seemingly only the first x tracks. However, it still displays the count-matrix for the remaining tracks, but they are naturally all empty (which may or may not be correct if you've played some of the tracks).

For the mentioned label (https://stream.resonate.coop/label/4088) it seems to fetch the first 15 tracks. I was not able to reproduce this for a different label (such as https://stream.resonate.coop/label/12300), there it seems to work as intended.

### Steps to reproduce behavior
1. Go to https://stream.resonate.coop/track/6991 play the track past the 45 second mark
2. See how the playcount increases on it
3. Go to https://stream.resonate.coop/label/4088 and see how the playcount is still 0

**Comment by fgblomqvist** [comment]
If this issue is due to missing data or something like that, then the bug is instead that this data is missing (are there submission fields that need to be marked as required? And so forth).

**Comment by fgblomqvist** [comment]
Looked into this some more and this is what's happening:
* It fetches all the "releases" for the label, which is only the first 4 albums (what's listed under the "Discography" title on the label page).
* It then fetches all the playcounts for the discography albums.
* Then it fetches the "remaining" albums (what's listed under "Various Artists" on the label page), however, it does not fetch the playcounts for these.

The question I have now is what's the difference between "Releases" and "Albums" and "Discography? And what does "Various Artists" have to do with it?

Looks like the code could be refactored a bit to reduce the different code-paths. It's in the `stores/labels.js` file.

**Comment by fgblomqvist** [comment]
I'll take a stab at this

**Comment by auggod** [comment]
Good catch! The `getLabelAlbums2` function is missing the part where we're fetching play counts
`getLabelAlbums` and `getLabelAlbums2` should be refactored into one single function. The first one fetches the releases as trackgroups.
The second function is only for fetching various artists albums. Various artists albums were not migrated to `track_groups`.

Also, the title should not be clickable as we can't display various artists albums on a single page. (no slug available)

**Comment by fgblomqvist** [comment]
Thanks for confirming @auggod.
Will see if I can get a PR up today.

Is there a page/discussion where I can get some info on this "Various Artists" stuff/differences between albums and "releases" etc?

**Comment by fgblomqvist** [comment]
I am working on this but getting a PR out "just like that" was clearly a bit overambitious :sweat_smile:.
It's always a bit complicated to reliably refactor code like this when there are no types but I am slowly making progress at least. Sooner or later.

**Comment by auggod** [comment]
@fgblomqvist I should be able to help, you can still draft a pull request.

**Comment by whatSocks** [comment]
(written here for posterity / testing purposes - NOT to suggest fixing this all at once)
There's a related issue with tracks with artists that only appear on `various` albums 

example:
artist: https://stream.resonate.coop/artist/4231
track: https://stream.resonate.coop/track/6990 -> can click view artist to get to 4231's page
album: Heritage Riddim here https://stream.resonate.coop/label/4088 -> click album title, get undefined page

**Comment by fgblomqvist** [comment]
@auggod Thanks, wrapping up the last bit tonight so should be able to get a PR up then, along with some commentary on the changes/what's potentially left.

@whatSocks the `undefined` issue will be "fixed" in my PR according to what @auggod proposed. As in, it should simply not be possible to click the album title.
