### ISSUE TITLE
[iOS only] "Learn" dropdown non-functional in mobile browser

### ISSUE THREAD

**Issue by peterklingelhofer** [resonatecoop/stream2own#168]
### Operating system
iOS

### Browser name and version
Firefox Daylight 97.0 (7635) and [stream-app](https://github.com/peterklingelhofer/stream-app), which uses Safari natively

### Expected behavior
Pressing the `Learn` dropdown at the top should display the dropdown visible when viewed in the desktop browser. This seems to be behaving as intended with the Google Chrome device toolbar emulating a phone, however.

### Actual behavior
Pressing `Learn` has seemingly no effect.

### Steps to reproduce behavior
Load https://stream.resonate.coop on your mobile device. Press `Learn` at the top.

On phone:
![IMG_9166](https://user-images.githubusercontent.com/60944077/154803578-302ff973-d061-4217-9c5f-bbdd95273e7d.jpg)

In Google Chrome device toolbar emulating a phone:
<img width="376" alt="Screen Shot 2022-02-19 at 7 48 12 AM" src="https://user-images.githubusercontent.com/60944077/154803585-99c4243b-c1fd-4948-9f01-863785e985f6.png">

**Comment by gsonnenf** [comment]
I am using an android Pixel 3a XL on Chrome and the listen menu bar worked as expected.

**Comment by peterklingelhofer** [comment]
> I am using an android Pixel 3a XL on Chrome and the listen menu bar worked as expected.

Thank you for reporting on this. Seems exclusive to iOS then. This is the case for me in both Firefox Daylight (Mobile) and using the [stream-app](https://github.com/peterklingelhofer/stream-app).

**Comment by auggod** [comment]
I'm quite sure it's related to the offen (offen.dev). It loads up an iframe and sometimes the element remains invisible while on top which cause the inability to click on the learn menu and more. I was able to replicate this locally.

**Comment by peterklingelhofer** [comment]
Attempting to hide the "Learn" menu for iOS mobile browsers and the iOS [stream-app](https://github.com/peterklingelhofer/stream-app) users, as pressing it does nothing. Running into this error:

```sh
◇ ReferenceError: navigator is not defined
    at Header.createElement (~/Dev/stream/beta/build/components/header/index.js:291:19)
    at Header.Nanocomponent.render (~/Dev/stream/node_modules/nanocomponent/index.js:53:29)
    at Choo._handler (~/Dev/stream/beta/build/elements/layout.js:32:51)
    at Choo._prerender (~/Dev/stream/node_modules/choo/index.js:259:18)
    at Choo.toString (~/Dev/stream/node_modules/choo/index.js:232:19)
    at render (~/Dev/stream/node_modules/jalla/lib/render.js:27:14)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async etag (~/Dev/stream/node_modules/koa-etag/index.js:27:5)
    at async ~/Dev/stream/node_modules/koa-conditional-get/index.js:15:5
```

```diff
diff --git a/beta/src/components/header/index.ts b/beta/src/components/header/index.ts
index 2301b66..05e962c 100644
--- a/beta/src/components/header/index.ts
+++ b/beta/src/components/header/index.ts
@@ -270,6 +270,10 @@ class Header extends Component<HeaderProps> {
       title: 'Resonate'
     }
 
+    const isIOS = (navigator !== undefined && 'userAgent' in navigator) &&
+      (navigator.userAgent.match(/iOS/) ??
+      (navigator.userAgent.match(/Mac/) && document !== undefined && 'ontouchend' in document))
+
     return html`
       <header role="banner" class="bg-white black bg-white--light black--light bg-black--dark white--dark white fixed sticky-l left-0 top-0-l bottom-0 right-0 w-100 z-9999 flex items-center bt bt-0-l bb-l bw b--mid-gray b--mid-gray--light b--near-black--dark" style="height:3rem">
         <nav role="navigation" class="relative dropdown-navigation--focus">
@@ -280,12 +284,15 @@ class Header extends Component<HeaderProps> {
               }))}
             </li>
             <li class="flex flex-auto-l w-100-l justify-center" role="menuitem">
-              <button title="Open learn menu" class="bg-transparent near-black near-black--light near-white--dark bn dropdown-toggle grow pa3">
-                <div class="flex justify-center items-center">
-                  <span>Learn</span>
-                  <div class="ph2">${icon('caret-down', { size: 'xxs' })}</div>
-                </div>
-              </button>
+              ${isIOS
+                    ? html`< button title = "Open learn menu" class="bg-transparent near-black near-black--light near-white--dark bn dropdown-toggle grow pa3" >
+                        <div class="flex justify-center items-center">
+                          <span>Learn</span>
+                          <div class="ph2">${icon('caret-down', { size: 'xxs' })}</div>
+                        </div>
+                        < /button>`
+                    : ''
+                }
               <ul role="menu" class="${bg} ba bw b--mid-gray b--mid-gray--light b--near-black--dark list ma0 pa0 absolute right-0 dropdown z-999 top-100" style="left:0;width:120px;">
                 <li>
                   <a class="link db w-100 ph3 pv2 bg-animate hover-bg-light-gray hover-bg-light-gray--light hover-bg-dark-gray--dark" href="https://resonate.coop/about" target="_blank">About</a>
```

**Comment by peterklingelhofer** [comment]
Maybe adding `tabindex="0"`?

https://stackoverflow.com/questions/66477748/focus-within-works-on-android-browser-but-not-ios

**Comment by peterklingelhofer** [comment]
Solution: https://github.com/resonatecoop/website/pull/41
