### ISSUE TITLE
Album pages doesn’t work

### ISSUE THREAD

**Issue by timotheegoguely** [resonatecoop/stream2own#19]
### Operating system
macOS 10.14.5

### Browser name and version
Chrome 74

### Expected behavior
Album pages should be working

### Actual behavior
All album links are broken: they all redirect to this url https://beta.resonate.is/albums/dezdez

<img width="1552" alt="404 Page not found" src="https://user-images.githubusercontent.com/8271134/59022728-a3e48580-884e-11e9-8708-6711d8d537ee.png">

### Steps to reproduce behavior
Clicking on any album title on a label page for example https://beta.resonate.is/labels/7929

**Comment by auggod** [comment]
Single albums pages are not implemented yet. Those links should not have been there in the first place.
This will be fixed in the next release wich adds pagination for most playlists, labels, albums etc...
I'll close when the update is released.
