### ISSUE TITLE
Confusing login UX with double Log In buttons

### ISSUE THREAD

**Issue by peterklingelhofer** [resonatecoop/stream2own#193]
### Operating system
Android

### Browser name and version
Unknown

### Expected behavior
On the login screen, the second log in button in the lower right hand corner should be hidden to avoid confusion.

### Actual behavior
On the login screen, the second log in button in the lower right hand corner is displayed.

### Steps to reproduce behavior
Press Log In on mobile.

![doubleloginbutton](https://user-images.githubusercontent.com/60944077/156487751-76d83948-46a5-447f-a1d7-1354930e106f.png)

**Comment by peterklingelhofer** [comment]
Tried to figure out how to hide the login button for users already on login page.
https://github.com/resonatecoop/stream/blob/97948c7a2d5fdcfca4a549735992e3d2eaf6db80/beta/src/components/header/index.ts#L222 might be the spot to do it, `location.pathname !== '/login'`, but `window` and `location` are `undefined` in that area it seems.

**Comment by auggod** [comment]
@peterklingelhofer You can use `state.href`. Also works on node.

```js
state.href !== '/login' ? html`<div></div>` : ''
```
