### ISSUE TITLE
[enhancement] Clarify credits balance display

### ISSUE THREAD

**Issue by raphraph** [resonatecoop/stream2own#203]
### Operating system
Ubuntu 21.10

### Browser name and version
Firefox 98.0b9

### Expected behavior
Always show credit with three digits after separator.
For example display `0.020` and not `0.02`

![example_credits_balance](https://user-images.githubusercontent.com/3306130/157226019-59b56663-c637-4844-a861-25a26c9ac2da.png)

### Actual behavior
When last digit is `0` it is not shown, so reading credit balance can be confusing.
Consistency in the number of digits displayed will help new users understand how their credit balance evolve as they listen to music.

### Steps to reproduce behavior
Listen to music and watch your credit balance go down ;)

**Comment by auggod** [comment]
I think this is localization related. It was really a bad idea to use an input type number to display the credits amount.
