### ISSUE TITLE
Possible to play a full unowned track an infinite amount of times as long as you have more than 0.002 credits

### ISSUE THREAD

**Issue by fgblomqvist** [resonatecoop/stream2own#217]
### Expected behavior
If I don't have enough credits to pay for a full listen for a track I don't yet own, I should only be able to listen to 45 seconds of it (the preview).

### Actual behavior
As long as I have more than 0.002 credits, I can freely listen to any unowned track, the full length, however many times I want without getting charged. Though, I don't get any more ownership shares of it.

### Steps to reproduce behavior
1. Ensure you have very few credits in your account, e.g. 0.0060.
2. Play a song that you don't yet own, that costs more than 0.0060 to play (e.g. the 2nd play or above).
3. Watch how you're able to listen to all of it, and how your credits don't decrease, and how your ownership shares don't increase.

This issue was hinted at by @peterklingelhofer [here](https://github.com/resonatecoop/stream/pull/213#issuecomment-1073050197).

**Comment by fgblomqvist** [comment]
I see two possible solutions here:
1. Query the back-end before starting every song to determine if you can afford a play of it or not.
2. Duplicate the business logic into the front-end as well so that it can determine on its own if the song can be afforded.

Number 2 feels wrong and prone to error (not to mention user manipulation, down the road anyway).
Number 1 can be simplified like this:
1. If the user is not signed in, they cannot afford a play.
2. If the song is free, they can afford a play.
3. If the song is owned, they can afford a play.
4. If the song is not free and the user has 0 credits, they cannot afford a play.
5. Else, query the back-end

Down the road, it could be optimized further by e.g. asking about the next song in the queue ~10 seconds before the current song ends, to prevent potential gaps (which probably only happens if you have a shitty connection).

Any ideas on this? I feel like this behavior needs to be figured out sooner rather than later since otherwise artists might feel like they can easily be shafted.

**Comment by fgblomqvist** [comment]
cc: @auggod @jackhajb

**Comment by auggod** [comment]
You may be running into a cache issue. The next api update will fix this issue.
Currently, we can add ?preview=true to the audio srcs to force the 45 secs snippets.

**Comment by fgblomqvist** [comment]
This seems to indeed have been fixed with the latest merge of the API changes.
