### ISSUE TITLE
Display name and email misleadingly appear directly editable

### ISSUE THREAD

**Issue by hakanto** [resonatecoop/stream2own#218]
Name
Display name and email misleadingly appear directly editable

Description
Text entry boxes appear on the Update Your Account page which are not directly editable: Display name and E-mail. Instead, you must click Change your display name or Change your email and navigate to other pages.

Example for Display Name entry box:

sercxi
sercxi
731×188 8.19 KB
This is confusing because this black entry box is always direcly editable across Resonate’s UI.

Due to the ID server’s design, it seems necessary that the user navigate elsewhere to change these settings. Thus, we should not use the black box UI here. We need to use a different presentation of the Display Name and Email which makes it clear they are not directly editable. Displaying only large text of the Display name and Email themselves, with no black box, would be a solution.

Steps to reproduce
Log in with account
Navigate to id.resonate.ninja/account
Click Display name or Email entry boxes to edit them
Expected Results vs Actual Results
Expected:

If not directly editable, information will not appear in the black box styling used across Resonate for editing information.

Actual:

I attempt to update my display name and email directly in the text boxes. Nothing changes.

Source URL
id.resonate.ninja/account

Environment
Brave 1.16.68

**Comment by peterklingelhofer** [comment]
Should this issue live over with the **`id`** repo's [issues](https://github.com/resonatecoop/id/issues)? Based on your source url at first glance I'm guessing the code that needs to be fixed is in the `id/frontend/src/components` folder over there. I could be wrong though.

**Comment by peterklingelhofer** [comment]
Closing this as I've opened the issue in the repository where it will need to be addressed: [id#64](https://github.com/resonatecoop/id/issues/64)

GitHub wouldn't let me transfer it for some reason.
