### ISSUE TITLE
Unable to buy a song

### ISSUE THREAD

**Issue by simonv3** [resonatecoop/stream2own#226]
### Operating system
Linux Mint

### Browser name and version
Firefox 98.02

### Expected behavior
I'm able to buy a song

### Actual behavior
Attempting to buy a song returns a 404 and "Something unexpected happened" pops up.

![image](https://user-images.githubusercontent.com/485583/163497670-7aff1244-adef-4a0d-a604-abea559dd11b.png)

This is the request that gets sent
```
POST https://stream.resonate.coop/api/v1/users/2359/plays/buy

{"tid":24804}

Response:
{"message":"No track found","data":null,"status":404}
```

### Steps to reproduce behavior
1. Be logged in
2. Go to https://stream.resonate.coop/artist/21109/release/refactor
3. Click on three dots of Little Bouncing Ball (first song)
4. Click on Buy Now in Menu that pops up
5. Click on Buy Now on the track detail page
6. Error appears.

**Comment by auggod** [comment]
Seems this issue went unnoticed for a bit of time. The v2 api is not affected. I have pushed a fix early this morning. It didn't affect all tracks.

**Comment by simonv3** [comment]
Awesome, looks like when I clicked on the steps now it went through!
