### ISSUE TITLE
Unable to top up account

### ISSUE THREAD

**Issue by sphinxc0re** [resonatecoop/stream2own#245]
### Operating system
Arch Linux

### Browser name and version
Firefox 103.0 (64-bit)

### Expected behavior
I can pay and top up my account

### Actual behavior
I just get the message: "Unexpected payment status"

### Steps to reproduce behavior
Try to pay and top up your account

**Comment by auggod** [comment]
We're using stripe on the backend to process topups. I can see your attempts to purchase credits were either cancelled or incomplete. Also, 3d secure may be triggered in your case and you didn't complete the process.
