### ISSUE TITLE
No changes on pages Browse:Artists and Browse:Labels

### ISSUE THREAD

**Issue by hakanto** [resonatecoop/stream2own#252]
Not sure if this is a bug.

On https://stream.resonate.coop/artists and https://stream.resonate.coop/labels there have been no noticeable changes in the artists and labels displayed in a very long time. Not sure why this is.

**Comment by auggod** [comment]
You're right, I found out there was still a condition on the track album art|album... 3-4 pages were missing. Just fixed this.
