### ISSUE TITLE
Infinite pagination

### ISSUE THREAD

**Issue by timotheegoguely** [resonatecoop/stream2own#26]
### Expected behavior
Pagination shouldn't contain empty pages.

### Actual behavior
Pagination on artists / albums / tracks pages is infinite.

<img width="544" alt="Infinite pagination" src="https://user-images.githubusercontent.com/8271134/59186537-609e5580-8b73-11e9-86e1-e67395ef3f1a.png">

### Steps to reproduce behavior

- Example on label page: [https://beta.resonate.is/labels/7929/artists?page=100](https://beta.resonate.is/labels/7929/artists?page=100)
- Example on artist’s albums page: [https://beta.resonate.is/artists/9350/albums?page=100](https://beta.resonate.is/artists/9350/albums?page=100)
- Example on artist’s tracks page: [https://beta.resonate.is/artists/9350/tracks?page=100](https://beta.resonate.is/artists/9350/tracks?page=100)

**Comment by auggod** [comment]
API need to be updated to return the number of pages to expect. Once we have that, i can add a `numberOfPages` prop on pagination component.

**Comment by auggod** [comment]
#27 Merged update to fix infinite pagination issue
