### ISSUE TITLE
Non-authed visitor unable to listen to entirety of "free" track

### ISSUE THREAD

**Issue by hakanto** [resonatecoop/stream2own#262]
Before migration, I believe non-authed visitor users were able to listen to entirety of tracks that are set as "free".

Post-migration, this no longer appears possible. Playback stops at 45 secs as is typical for "Paid" tracks. 

Steps to reproduce:

1. Go to stream.resonate.coop while not logged into an account.
2. Attempt to play [Can be reclaimed](https://stream.resonate.coop/track/23552) or [Jaded Forum: Episode 9](https://stream.resonate.coop/artist/21687/release/jaded-forum-episode-9).
3. Track playback will stop at 45 secs although the track is set as "free".

**Comment by auggod** [comment]
I have already pushed a fix. Thank you for the heads up.
