### ISSUE TITLE
In playback bar, artist name displays as "Drafts"

### ISSUE THREAD

**Issue by hakanto** [resonatecoop/stream2own#263]
![drafts](https://user-images.githubusercontent.com/72839766/184694056-82d7d068-e663-4eca-a627-04d136014e7e.png)

I've triplechecked that the artist display name on dash.resonate.coop is set as "Jaded Forum". Unsure why during playback, the artist name is displaying as "Drafts". Only happens during playback.

Only seems to affect Jaded Forum: Episode 9 -- https://stream.resonate.coop/artist/21687/release/jaded-forum-episode-9

**Comment by auggod** [comment]
Just fixed the problem. Drafts was set as the track artist (it was in the audio file metadata)
