### ISSUE TITLE
Direct links to tracks or artists doesn’t work in Chrome and Safari

### ISSUE THREAD

**Issue by timotheegoguely** [resonatecoop/stream2own#32]
### Operating system
macOS 10.14.6

### Browser name and version
Chrome Version 76.0.3809.132
Safari 12.1.2

### Expected behavior
Links to [tracks](https://beta.resonate.is/tracks/13247) or [artists](https://beta.resonate.is/artists/650) should display the actual track page on Resonate app.

### Actual behavior
When I click on a track or artist URL from a webpage – like the links on [this page](https://hackmd.io/5gl0AQ-oRLafBXFqsPg4ig) – I’m landing on a blank page of the app (cf. screenshot bellow). And refreshing the page and disable all blockers doesn’t change anything. It works well with Firefox but not with Chrome and Safari.

<img width="720" alt="Chrome and Safari blank app page." src="https://user-images.githubusercontent.com/8271134/64104407-75eede80-cd74-11e9-9557-30e67001f50d.png">

**Comment by auggod** [comment]
I think this issue is related to #31.
