### ISSUE TITLE
Play button in the player bar becomes black in dark mode 

### ISSUE THREAD

**Issue by blushi** [resonatecoop/stream2own#35]
### Expected behavior
The play button should stay white in dark mode.

### Actual behavior

> With the dark theme, whenever I press the Pause button, the Play button displayed is black. Which against the dark grey background is very difficult to make out. Please consider increasing the contrast between the Play button and the background when using the dark theme.

![image](https://user-images.githubusercontent.com/3149358/65887305-03d2df00-e39e-11e9-867c-bfd22e8a94a9.png)

### Steps to reproduce behavior
Play a track in dark mode then press pause (from the track player or the player bar).

**Comment by auggod** [comment]
This is being taken care of. An update is coming shortly to fix this issue.

**Comment by auggod** [comment]
Issue has been fixed as of today.
