### ISSUE TITLE
Improve random feature

### ISSUE THREAD

**Issue by blushi** [resonatecoop/stream2own#37]
### Expected behavior
Clicking again on "random" when already on the random page should load new random tracks.

### Actual behavior
It's doing nothing.

### Steps to reproduce behavior

> when i choose "random" and start the last track and use the forward button for the next track ... there is no next track coming.
> when i click "random" again ... there are no new tracks showed. that doesn't help to listen to music.

**Comment by peteratomic** [comment]
I've noticed this as a general issue across the PWA... that being in a section (like "New") and then clicking the "new" link also has no result. You have to click some other link, go to a different section, then go back as a "link to the section where I already am" isn't understood by the PWA.

**Comment by auggod** [comment]
A link is not a button. I don't expect the page to change at all when clicking a link which leads to the exact same page. We can change this link to a button and make it obvious that it will fetch new content. Was this feature documented before when we updated the player back in 2017?

**Comment by peteratomic** [comment]
Sorry, maybe I shouldn't have tried to combine the issues. Sure my example is a rare case and certainly reveals my lack of technical understanding of how a PWA works. But from a user perspective, when you mouse over a link that you've clicked on in the past, and the mouse hand reacts (as if its a link) then it (IMHO) should perform like a link. With standard pages this happens all the time. You can be on a page and click a menu link to the same page and it simply acts as a refresh.

That said, Marie's issue is more pressing as its definitely something people would expect... that clicking "random" should refresh the list again.
