### ISSUE TITLE
lerna does not install dependencies

### ISSUE THREAD

**Issue by rcffc** [resonatecoop/stream2own#38]
### Operating system
Windows 10

### Browser name and version
Chrome 79.0

### Expected behavior
`lerna bootstrap` should install dependencies.

### Actual behavior
`lerna bootstrap` throws
```
npm ERR! addLocal Could not install C:\Users\p_jia\projects\stream2own\packages\tools
npm ERR! Windows_NT 10.0.17763
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\p_jia\\projects\\stream2own\\node_modules\\npm\\bin\\npm-cli.js" "install" "--no-package-lock"
npm ERR! node v12.14.1
npm ERR! npm  v2.15.12

npm ERR! No version provided in package.json
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\p_jia\projects\stream2own\npm-debug.log
lerna ERR! npm install --no-package-lock exited 1 in 'stream2own'
lerna ERR! npm install --no-package-lock exited 1 in 'stream2own'
```

### Steps to reproduce behavior
I uninstalled node.js and nvm and deleted folders that relate to them.
Then I installed nvm with version 12.14.1 and ran
```
npm i lerna -g
lerna bootstrap
```
but it gave me the same error.
Then I uninstalled nvm and tried installing node directly, but the same problem persists.

```
node -v
> v12.14.1

npm -v
> 6.13.4
```

I suspect it might have something to do with _npm v2.15.12_...

**Comment by auggod** [comment]
The installation fails because the root `package.json` file does not contain a version field. This is the first time I see this error for a private package.
You may checkout 'develop' branch. Master branch is way behind. I added a "0.0.0" version number as a placeholder.
Also make sure to use the latest version of npm and lerna.

**Comment by rcffc** [comment]
Installed the latest npm version 6.13.6 and switched to dev. But still, no luck:

````
lerna notice cli v3.20.2
lerna info versioning independent
lerna info bootstrap root only
npm ERR! addLocal Could not install C:\Users\p_jia\projects\stream2own\packages\tools
npm ERR! Windows_NT 10.0.17763
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\p_jia\\projects\\stream2own\\node_modules\\npm\\bin\\npm-cli.js" "install" "--no-package-lock"
npm ERR! node v13.8.0
npm ERR! npm  v2.15.12

npm ERR! No version provided in package.json
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\p_jia\projects\stream2own\npm-debug.log
lerna ERR! npm install --no-package-lock exited 1 in 'stream2own'
lerna ERR! npm install --no-package-lock exited 1 in 'stream2own'
```
`

**Comment by auggod** [comment]
Ok, it's complaining only about "tools" package. You may try again after pulling the changes from "develop".

**Comment by rcffc** [comment]
Thanks, that has fixed the problem!
