### ISSUE TITLE
Song context menu hidden by music player

### ISSUE THREAD

**Issue by webwelten** [resonatecoop/stream2own#40]
### Operating system
OSX

### Browser name and version
Firefox 74

### Expected behavior
Menu should be visible above the music player or open in the other direction (top).

### Actual behavior
Song context menu hidden by music player

### Steps to reproduce behavior
Scroll a songlist to the bottom and try using the menu on the right.

<img width="832" alt="Screenshot 2020-03-29 at 15 08 57" src="https://user-images.githubusercontent.com/3693161/77883851-37ff5d80-7264-11ea-8dec-d39ce0f70d8a.png">

**Comment by auggod** [comment]
It lacks some padding in the bottom of this view, got to increase it.
