### ISSUE TITLE
Icon purpose not clear or ambigous

### ISSUE THREAD

**Issue by webwelten** [resonatecoop/stream2own#42]
### Operating system
OSX

### Browser name and version
Firefox 74

### Expected behavior
Don't know yet.

### Actual behavior
The icon is also used as loading indicator, which makes it ambiguous.
It doesn't a label on hover.
It's not self-explanatory if you're just exploring the app without being registered.

### Steps to reproduce behavior

<img width="1280" alt="Screenshot 2020-03-28 at 21 48 55" src="https://user-images.githubusercontent.com/3693161/77884760-fe2f5680-7265-11ea-8c03-9ed373a2ee7c.png">

**Comment by auggod** [comment]
Thank you for this. I think, at least it should be hidden for non registered users.
Also + 1 for the label. It was planned to added a label as shown in the screenshot below.
<img width="472" alt="Screenshot 2020-04-02 at 21 19 41" src="https://user-images.githubusercontent.com/1394538/78292674-b50e2980-7527-11ea-99c7-3694b3bad18b.png">

This should be added in a future release.
