### ISSUE TITLE
0.3-0.4-0.5 Create User Group (profile)

### ISSUE THREAD

**Issue by auggod** [resonatecoop/stream2own#52]
As a user, I want to be able to create a new user group I'll be the owner of (either right after sign up/welcome page or from 9. Account Settings):

0.3 - Assign a user group type: artist, label or neither https://www.figma.com/file/CrTEIjth3aD0yJ6MiyMK4V2B/0.0-Onboarding?node-id=1%3A80

0.4 - Fill out basic info: display name, short bio, profile picture, header image, location, links https://www.figma.com/file/CrTEIjth3aD0yJ6MiyMK4V2B/0.0-Onboarding?node-id=1%3A107

0.5.1 - As a label user group, I want to add artists https://www.figma.com/file/CrTEIjth3aD0yJ6MiyMK4V2B/0.0-Onboarding?node-id=1%3A80

0.5.2 - As an artist user group, I want to add music genres, members (with role and display name Design added - AlexC), incoming payment methods (rather bank account details EU, Stripe account details outside EU, ask @mattk for more details regarding payments), recommended artists https://www.figma.com/file/CrTEIjth3aD0yJ6MiyMK4V2B/0.0-Onboarding?node-id=1%3A164

**Comment by hakanto** [comment]
moved to https://community.resonate.is/t/create-user-group-profile/1266
