### ISSUE TITLE
1.0 Feed

### ISSUE THREAD

**Issue by auggod** [resonatecoop/stream2own#53]
As a user, I want to see my Feed first after signing up/logging in, so that I can check out:

- Last added albums and tracks from followed artist user groups
- Last added playlists from followed user groups (NB handled from back-end: if they set their playlists as public)
- Last recommended artists from followed user groups (if they set their recommended artists as public)
- Latest news from Resonate
- If my Feed is empty, I want to be presented with a welcome message.

https://www.figma.com/file/Uzd8j1ff6sH9Y2veYne8nVHD/1.0-Feed

**Comment by hakanto** [comment]
Added to https://community.resonate.is/t/user-feed/1263

Added "User" to name: "User Feed"
