### ISSUE TITLE
2.0 Discovery

### ISSUE THREAD

**Issue by auggod** [resonatecoop/stream2own#54]
As a user, I want to access a "Discover" page so I can see:

- Currently featured artist
- Currently featured label
- Currently featured playlist
- Currently featured genres each associated with a particular album
- Previously featured

https://www.figma.com/file/MvPnWW13aStoInVXyaikMpxQ/2.0-Discovery (i2)

**Comment by peteratomic** [comment]
IMHO the term "discover" should be avoided as Discover Weekly has been a Spotify brand for years. 

That said, I don't think we should worry about it for now. Can be discussed in the forums after launch. Much better to get some community participation on this since we're trying to completely reframe the values and relationships represented here.

**Comment by milieuChris** [comment]
This discovery piece is my #1 complaint with music services today. Google's offering prior to moving that team to YouTube almost worked as the radio stations did a god job of mixing up the music. Pandora almost works in the same way, by offering up "radio stations" based on some starting point. I believe we can do better than that 20 years on however.

For what it is worth, i was personally responsible for the the music recommendation systems at Radio Free Virgin and Virgin Digital, from the data ontology and backend systems that were controlled by the music experts, to the services that the desktop and web players used to deliver the music to listeners, and the desktop player itself.

I can volunteer a few hours here and there to help with any research you are considering to inform the development of this feature. Just message me here, or i think Peter (@peteratomic) has a Twitter DM for me. I code too, but have less time for that currently as i'm deep in to other projects. This one matters a great deal to me though. Wish you all the best!

**Comment by auggod** [comment]
To be clear, we haven't worked much on design since summer 2018. I'm just migrating old issues coming from our self hosted gitlab so we can discuss and rework them. The featured artists, labels, etc.. is something we have on Resonate for a long time already which has been difficult to maintain. In the short term, we're coming with a long awaited playlisting feature.

**Comment by peteratomic** [comment]
@milieuChris are you on the Resonate community forum? Just posted a thread there on this topic: https://community.resonate.is/t/discovery-as-a-menu-item-general-music-search-term/922

Would be AMAZING to have your input on this!

**Comment by hakanto** [comment]
moved to https://community.resonate.is/t/discovery-page/1265

Added a bit of context to the post, explaining that little work has been done on this story since 2018 and that we are looking for community input/vision on it.
