### ISSUE TITLE
3.0-3.1-3.2-3.3 Library

### ISSUE THREAD

**Issue by auggod** [resonatecoop/stream2own#55]
As a user, I want to access my Library in order to consult my:

- Favourites tracks
- Owned tracks (renaming to collection)
- Playlists
- History
https://www.figma.com/file/YKXtA7E9WSh1mYqGVLWnK0Em/3.0-Library

**Comment by auggod** [comment]
Owned tracks will be renamed to 'Collection'

**Comment by hakanto** [comment]
https://community.resonate.is/t/user-music-library/1264

Changed name to "User Music Library".
