### ISSUE TITLE
4.0 Search

### ISSUE THREAD

**Issue by auggod** [resonatecoop/stream2own#56]
As a user, I want to be able to search by:

- user group display name (can be user [people], artist, label)
- genre name
- track group title (can be release, playlist)
- track title.
Then I want to be presented with a list of all results or grouped results by:

artists: click on result item => profile page
album: click on result item => album page
labels: click on result item => profile page
people (user with a public user group profile): click on result item => profile page
playlists: click on result item => playlist page
tracks Design updated - AlexC
https://www.figma.com/file/LpV46qgwMmWuwx7bBRKea4o6/4.0-Search

**Comment by hakanto** [comment]
moved to https://community.resonate.is/t/search-bar/1260
