### ISSUE TITLE
5.1 Artist Profile

### ISSUE THREAD

**Issue by auggod** [resonatecoop/stream2own#57]
As a user, I want to check a public artist profile page I don't own that contains:

- Banner image if exists
- Profile picture
- Name
- Follow button (not in 7.x)
- Short bio if exists (not in 7.x)
- Highlights if exists: list of highlighted tracks (top tracks by number of plays)
- Featured album if exists
- Discography if exists: list of albums => click on album leads to album page
- Recommended artists if exists => click on artist leads to album artist (not in 7.x)
- Member of: label lists if exists (still only one label per account in 7.x)
- Members: list of members (musicians for instance) Design updated - AlexC (not in 7.x)
- Bio if exists
- Links if exist

https://www.figma.com/file/L4fbrgOe1PYWD3Gb7WpCZvWr/5.0-Profiles?node-id=49%3A1

**Comment by hakanto** [comment]
moved to https://community.resonate.is/t/artist-profile/1257
