### ISSUE TITLE
5.2 User Profile

### ISSUE THREAD

**Issue by auggod** [resonatecoop/stream2own#58]
As a user, I want to check a public user profile page I don't own that contains:

- Banner image if exists
- Profile picture
- Name
- Follow button (not in 7.x)
- Short bio if exists
- Featured playlist if exists
- Playlists if exist: list of playlists => click on playlist leads to playlist page
- Recommended artists if exists => click on artists leads to artist page (not in 7.x)
- Favourites if exists
- Bio if exists
- Links if exist
https://www.figma.com/file/L4fbrgOe1PYWD3Gb7WpCZvWr/5.0-Profiles?node-id=48%3A0

**Comment by hakanto** [comment]
moved to https://community.resonate.is/t/user-profile/1256
