### ISSUE TITLE
5.3 Label Profile

### ISSUE THREAD

**Issue by auggod** [resonatecoop/stream2own#59]
As a user, I want to check a public label profile page I don't own that contains:

- Banner image if exists
- Profile picture
- Name
- Follow button
- Short bio if exists
- Featured album if exists
- Artists if exist: list of artists => click on artists leads to artist page
- Discography: list of albums => click on album leads to album page
- Playlists if exist: list of playlists => click on playlist leads to playlist page
- Recommended artists if exists => click on artists leads to artist page
- Bio if exists
- Links if exist
https://www.figma.com/file/L4fbrgOe1PYWD3Gb7WpCZvWr/5.0-Profiles?node-id=49%3A5

**Comment by hakanto** [comment]
moved to https://community.resonate.is/t/label-profile/1255
