### ISSUE TITLE
6.0 Album Page

### ISSUE THREAD

**Issue by auggod** [resonatecoop/stream2own#60]
As a user, I want to consult an album page that contains:

- Artwork
- Album name
- Artist name
- Tracklist
- Label name if exists: on click => to Label Profile page
- Release year
- Artwork credits if exists: if user public profile - on click => to User Profile page
- Other credits
https://www.figma.com/file/SDjDuZ7UV0AMRwsl9FXu0DFa/6.0-Album-Page

**Comment by justin-hackin** [comment]
Related: as a user, I would like to be able to play only a single album.  My expectation is that playing from the album page will do this.

**Comment by hakanto** [comment]
moved to https://community.resonate.is/t/album-page/1254
