### ISSUE TITLE
7.0 Playlist Page

### ISSUE THREAD

**Issue by auggod** [resonatecoop/stream2own#61]
As a user, I want to consult a public playlist page that contains:

- Banner image
- Playlist name
- Number of tracks
- User profile name and avatar
- If owner of the playlist: Edit button https://www.figma.com/file/Y6lIx4Tfo8p3A4XgtNCfzbEm/7.0-Playlist-Page?node-id=36%3A1527. Leads to version of 3.4 CREATE PLAYLIST view for editing.
- Tracklist
https://www.figma.com/file/Y6lIx4Tfo8p3A4XgtNCfzbEm/7.0-Playlist-Page?node-id=25%3A450

**Comment by hakanto** [comment]
moved to https://community.resonate.is/t/playlist-page/1253
