### ISSUE TITLE
3.4 Create Playlist

### ISSUE THREAD

**Issue by auggod** [resonatecoop/stream2own#62]
As a user, I want to be able to create a new playlist and set:

- Title
- Header image
- Privacy: checkbox Private/Public
- Public disabled if user does not have a public profile (link to "Create a profile now") https://www.figma.com/file/Y6lIx4Tfo8p3A4XgtNCfzbEm/7.0-Playlist-Page?node-id=36%3A1732
- If user has multiple public profiles, there is a dropdown to choose which one will own the new playlist https://www.figma.com/file/Y6lIx4Tfo8p3A4XgtNCfzbEm/7.0-Playlist-Page?node-id=36%3A1234

**Comment by hakanto** [comment]
moved to https://community.resonate.is/t/create-playlist/1258
