### ISSUE TITLE
9.4 Analytics

### ISSUE THREAD

**Issue by auggod** [resonatecoop/stream2own#63]
As a artist/label user group owner or member, I want to be able to check track analytics as a table with the following columns: (for label user group, per artist)

- track
- total streams
- paid, previews
- credits earned
- artist share
- resonate share
Design updated - AlexC https://www.figma.com/file/czlMLbAWrrHbSQuoQWCeCJk6/9.0-Settings?node-id=7%3A99 data table / empty state?

**Comment by auggod** [comment]
This is part of upload tool (or dashboard).

**Comment by hakanto** [comment]
moved from https://community.resonate.is/t/artist-analytics/1259

added "Artist" to title: Artist Analytics, to distinguish from User/Listener Analytics
