### ISSUE TITLE
9.2. Credits

### ISSUE THREAD

**Issue by auggod** [resonatecoop/stream2own#65]
As a user, I want to know:

- my credits balance
- average listening hours equivalent
- number of owned tracks
- number of supported artists
- Listening time (not in 7.x)
- Add credits

https://www.figma.com/file/czlMLbAWrrHbSQuoQWCeCJk6/9.0-Settings

**Comment by hakanto** [comment]
moved to https://community.resonate.is/c/platform/player/53
