### ISSUE TITLE
9.2 Add Credits

### ISSUE THREAD

**Issue by auggod** [resonatecoop/stream2own#66]
As a user, I want to be able to:

- add credits by choosing the € amount and seeing the equivalent credits. Design updated - AlexC Preset amounts or free input? https://www.figma.com/file/czlMLbAWrrHbSQuoQWCeCJk6/9.0-Settings?node-id=7%3A149
- pay using different payment options: Stripe, Resonate token (not mastercard, visa or paypal as in the current design as of 07/16/2018) https://www.figma.com/file/czlMLbAWrrHbSQuoQWCeCJk6/9.0-Settings?node-id=7%3A221
- get payment status popup (https://www.figma.com/file/czlMLbAWrrHbSQuoQWCeCJk6/9.0-Settings?node-id=7%3A313 success here)

**Comment by hakanto** [comment]
moved to https://community.resonate.is/t/add-credits/1216
