### ISSUE TITLE
9.1 Account Settings

### ISSUE THREAD

**Issue by auggod** [resonatecoop/stream2own#67]
As a user, I want to be able to:

- change my email address
- change full name Design added - AlexC
- change username Design added - AlexC
- see my list of existing profiles, edit, delete them  (not in 7.x)
- add a new profile (not in 7.x)
- change password
- set newsletter notification Design added - AlexC suggestion: could be a simple check box
- delete account Design added - AlexC suggestion: a simple button with a confirm alert if clicked
https://www.figma.com/file/czlMLbAWrrHbSQuoQWCeCJk6/9.0-Settings?node-id=2%3A151

**Comment by angusmcleod** [comment]
Moved to https://github.com/resonatecoop/id/issues/21

**Comment by hakanto** [comment]
moved to https://community.resonate.is/t/user-account-settings/1262

Added "User" to name: User Account Settings
