### ISSUE TITLE
10.0 Upload tracks

### ISSUE THREAD

**Issue by auggod** [resonatecoop/stream2own#68]
As an artist or a label user group owner, I want to be able to upload a new release:

Release info:
- select profile if owner of more than one (required)
display artist (could be different from profile display name, in the case of a compilation for example)
- title (required)
- artwork (required)
- about
- label (required)
- genres
- release date (required)
- catalog number
- ? total volumes
- ? territories
- ? C and P line year and text
- ? right expiry date
- checkbox "All tracks 100% written by me or my band. NO COVERS." with link to equivalent of 

https://resonate.is/uploading-cover-songs/ (required)

Add tracks:

- by selecting or dropping files
- upload state: to be discussed with back-end dev
- arrange track order and set featured track(s) (highlights)
- edit titles

Track metadata DESIGN UPDATED:

- free/paid
- add Artists (default artist = selected profile in 1. if of type artist)
- Release added to Discography: album page with message

DESIGN UPDATED If I have more than 30 track

**Comment by hakanto** [comment]
moved to https://community.resonate.is/t/upload-tracks/1215
