### ISSUE TITLE
9.5 Edit User Group profile

### ISSUE THREAD

**Issue by auggod** [resonatecoop/stream2own#69]
As a User Group Owner, I want to be able to edit my User Group info from the settings:

- Name
- if User Group of type "user": change type to artist or label
- Location (BE note: query User/Track API address search autocomplete endpoint, it uses Algolia Places API https://community.algolia.com/places/)
- Add/Remove links
- Upload profile picture and header image
- Add/Remove music genres

Privacy:

- available for all User Groups: public
only available for User Groups of type "user": display supported artists, display owned music

Releases:

- Upload new release
- Edit + Delete existing releases DESIGN UPDATED
- if User Group NOT of type "user", Add/Remove Members/Artists:
- if User Group of type "artist": with role and display name
- if User Group of type "label": side note from back-end dev - use UserGroup service AddMembers endpoint as well. DESIGN UPDATED
- if User Group of type "artist": DESIGN UPDATED
- Add/Remove "Member of" or "Label" (decide on the wording to use)
- Edit Publisher/M

**Comment by hakanto** [comment]
moved to https://community.resonate.is/t/edit-user-group-profile/1261/2
