### ISSUE TITLE
Rich Social Sharing

### ISSUE THREAD

**Issue by Jake-Gillberg** [resonatecoop/stream2own#7]
Link previews currently don't show artist specific content.

To get pretty looking previews, we need to serve static content to webcrawlers.

This looks like a good example nginx configuration to decide whether or not to pre-render, found in relationship to [prerender.io](https://prerender.io/) which looks like it has a service that can auto-render pages, but could be replaced by a custom endpoint.
https://gist.github.com/thoop/8165802

**Comment by Jake-Gillberg** [comment]
I successfully used a locally running prerender server (port 3000) to return a static page using a modified version of beta.resonate.localhost.conf in the style of the above example:

```
if ($http_user_agent ~* "googlebot|bingbot") {
      set $prerender 1;
      set $site "http://127.0.0.1:3000";
      rewrite .* /$scheme://$host$request_uri? break;
    }
    if ($prerender = 0) { 
      set $site "https://127.0.0.1:8080";
    }
    proxy_pass $site;
  }
```

**Comment by Jake-Gillberg** [comment]
To get prerender running locally:
```
git clone https://github.com/prerender/prerender.git
cd prerender
npm install
node server.js
```

**Comment by peteratomic** [comment]
Looked briefly at their service. My only concern would be caching. If an artist or label uploads a new file (song, album cover, profile image) and then expects that change to be live instantly, then we'd have a huge problem. If there's a way to do dynamic cache clearing on edits, then it could work, although I wonder how expensive it would get if we're essentially clearing the cache dozens of times a day. (1 day pricing is around $84 at our current content level.)

**Comment by peteratomic** [comment]
@auggod checked and saw there's a way to do manual cache clearing. So then its simply a thing of making sure that every time an artist or label updates a page, those are cleared instantly.

**Comment by auggod** [comment]
Also, there is another option available and cheaper for high volumes: https://www.prerender.cloud

My original idea to accomplish this is to use SSR capabilities of `bankai` which is the compiler we use as dev server and js bundler (browserify based).
Bankai has an [api](https://github.com/choojs/bankai#api) to setup more custom transforms based on routes, sadly this is not very well documented.

For changing meta tags we may use this choo plugin from `jallajs`:
https://github.com/jallajs/choo-meta

`jallajs` looks really promising as a replacement for `bankai`. I'm currently looking into it to see how it fits with our needs.

**Comment by Jake-Gillberg** [comment]
Another option would be to try and self-run a prerender server and see if we could handle the volumes. Especially since the prerenderer going down wouldn't impact site availability, just the crawler previews.

In #10 I just dropped in choo-meta. I suppose the next step would be to start pushing more stuff into the metadata as described in this document: https://docs.google.com/document/d/1e6utQ25uyb6qfZls_Jpdr5FI_YGi_nBAwJrYjB8rLAo/edit.

**Comment by auggod** [comment]
Merged #10

**Comment by auggod** [comment]
Discussion about implementing prerender.io server should be closed.
In the following branch: [jalla](https://github.com/resonatecoop/stream2own/tree/jalla), I replaced bankai with jalla (still pre-release)
Jalla is especially useful because it has now a `prefetching data` feature. Read more about this here: https://github.com/jallajs/jalla#prefetching-data
Should we start a new issue called `prefetching data` and close this one? @marie

**Comment by blushi** [comment]
@auggod yes I'll close this issue and you can create a new one `prefetching data`.
