### ISSUE TITLE
On Discovery Page, header featured artist is not rotating through all featured albums

### ISSUE THREAD

**Issue by hakanto** [resonatecoop/stream2own#84]
### Operating system
Pop!_OS 20.10

### Browser name and version
Version 1.16.68 Chromium: 86.0.4240.111 (Official Build) (64-bit)

### Expected behavior
On [Discovery](https://beta.stream.resonate.coop/discovery) page, the featured artist at top of page is randomly selected from the 15 featured albums.

### Actual behavior
On [Discovery](https://beta.stream.resonate.coop/discovery) page, the featured artist at top of page is randomly selected only from the first 4 featured albums and not the other 11.

### Steps to reproduce behavior
Refresh page repeatedly.

**Comment by fgblomqvist** [comment]
Does this apply anymore? There doesn't seem to be a "featured artist" at the top of that page

**Comment by hakanto** [comment]
@fgblomqvist Thanks for highlighting this. No, doesn't apply anymore. Closing issue.
