### ISSUE TITLE
On private playlists, thumbnail album art for tracks is sometimes not displaying

### ISSUE THREAD

**Issue by hakanto** [resonatecoop/stream2own#86]
### Operating system
Pop!_OS 20.10

### Browser name and version
Version 1.16.68 Chromium: 86.0.4240.111 (Official Build) (64-bit)

### Expected behavior
On a playlist page that has tracks added to it and has not been made public, I'd expect thumbnail album art to load next to each track (like on all pages).

### Actual behavior
On a playlist page that has tracks added to it and has not been made public, occasional thumbnail art is not displaying and is instead showing a "broken/missing image" placeholder where the thumbnail should be.

### Steps to reproduce behavior
1. Create playlist (I used [To All Believers](https://beta.stream.resonate.coop/track/20614) as track 1).
2. Add [broken master](https://beta.stream.resonate.coop/track/803) to the playlist.
3. Go to the playlist's page; album art for *broken master* is missing.
4. Click *Edit*
5. Uncheck *Private*
6. Return to playlist's page
7. thumbnail art appears for *broken master*

**Comment by auggod** [comment]
Issue was fixed in production.
