### ISSUE TITLE
Changing theme causes PWA app to appear empty/blank

### ISSUE THREAD

**Issue by hakanto** [resonatecoop/stream2own#87]
> @auggod: "Open and test app as PWA on both desktop and mobile if possible. I have noticed that if you change theme while in PWA on desktop (Chrome/Brave) there's only a blank page. After restarting the app, the theme is properly applied. Here is how it looks with Chrome on macOS.

![heeeeeeyup](https://user-images.githubusercontent.com/72839766/120395328-724a0c00-c2fa-11eb-91c1-6dec2a0b79f1.jpeg)

> This bug does not appear to be present on latest Chrome. Problem still happening on Brave.

**Comment by auggod** [comment]
Closing as I have not been able to reproduce this issue again with newer versions of Chrome.
